from pathlib import Path

path = Path('app/videos/page.tsx')
lines = path.read_text().splitlines()
start = 595
end = 712
new_block = [
"                        {activeTab === 'notes' && (",
"                            <div className=\"space-y-6\">",
"                                <div className=\"rounded-3xl border border-border bg-card p-6\">",
"                                    <div className=\"flex flex-col gap-4\">",
"                                        <div className=\"flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between\">",
"                                            <div>",
"                                                <h3 className=\"text-lg font-semibold\">My Notes</h3>",
"                                                <p className=\"mt-1 text-sm text-muted-foreground\">Write, save, edit, and delete notes for this lesson.</p>",
"                                            </div>",
"                                            <div className=\"flex items-center gap-2\">",
"                                                <button",
"                                                    type=\"button\"",
"                                                    onClick={() => setActiveTab(null)}",
"                                                    aria-label=\"Close notes\"",
"                                                    className=\"inline-flex h-9 w-9 items-center justify-center rounded-full border border-border bg-background text-muted-foreground transition hover:bg-red-50 hover:text-red-600\"",
"                                                >",
"                                                    <X className=\"size-4\" />",
"                                                </button>",
"                                                <button",
"                                                    type=\"button\"",
"                                                    onClick={handleSaveNotes}",
"                                                    className=\"inline-flex items-center rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white transition hover:bg-primary/90\"",
"                                                >",
"                                                    {editingNoteId ? 'Update Note' : 'Save Note'}",
"                                                </button>",
"                                            </div>",
"                                        </div>",
"", 
"                                        <div className=\"grid gap-4 sm:grid-cols-[1fr_auto]\">",
"                                            <label className=\"flex flex-col gap-2 text-sm text-muted-foreground\">",
"                                                Text color",
"                                                <input",
"                                                    type=\"color\"",
"                                                    value={noteColor}",
"                                                    onChange={(event) => setNoteColor(event.target.value)}",
"                                                    className=\"h-10 w-full cursor-pointer rounded-lg border border-border bg-background\"",
"                                                />",
"                                            </label>",
"                                            <label className=\"flex flex-col gap-2 text-sm text-muted-foreground\">",
"                                                Upload image",
"                                                <input",
"                                                    type=\"file\"",
"                                                    accept=\"image/*\"",
"                                                    onChange={handleNoteImageChange}",
"                                                    className=\"rounded-lg border border-border bg-background px-4 py-2 text-sm text-foreground\"",
"                                                />",
"                                            </label>",
"                                        </div>",
"", 
"                                        <textarea",
"                                            value={noteText}",
"                                            onChange={(event) => setNoteText(event.target.value)}",
"                                            placeholder=\"Write your lesson notes here...\"",
"                                            style={{ color: noteColor }}",
"                                            className=\"min-h-[180px] w-full rounded-3xl border border-border bg-background p-4 text-sm leading-6 outline-none transition focus:border-primary\"",
"                                        />",
"", 
"                                        {noteImageUrl && (",
"                                            <img",
"                                                src={noteImageUrl}",
"                                                alt=\"Uploaded note\"",
"                                                className=\"w-full rounded-3xl object-cover\"",
"                                            />",
"                                        )}",
"                                    </div>",
"                                </div>",
"", 
"                                <div className=\"space-y-4\">",
"                                    <div className=\"flex items-center justify-between\">",
"                                        <h3 className=\"text-lg font-semibold\">Saved Notes</h3>",
"                                        <span className=\"text-sm text-muted-foreground\">{lessonNotes.length} note{lessonNotes.length === 1 ? '' : 's'}</span>",
"                                    </div>",
"                                    {lessonNotes.length === 0 ? (",
"                                        <div className=\"rounded-3xl border border-dashed border-border bg-card p-6 text-sm text-muted-foreground\">",
"                                            No notes saved yet for this lesson.",
"                                        </div>",
"                                    ) : (",
"                                        <div className=\"grid gap-4\">",
"                                            {lessonNotes.map((note) => (",
"                                                <div key={note.id} className=\"rounded-3xl border border-border bg-background p-4 shadow-sm\">",
"                                                    <div className=\"flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between\">",
"                                                        <div>",
"                                                            <p className=\"text-sm text-muted-foreground\">{new Date(note.timestamp).toLocaleString()}</p>",
"                                                            <p className=\"mt-2 whitespace-pre-wrap text-sm\" style={{ color: note.color }}>",
"                                                                {note.text}",
"                                                            </p>",
"                                                        </div>",
"                                                        <div className=\"inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-medium\" style={{ color: note.color, borderColor: note.color }}>",
"                                                            Selected color",
"                                                        </div>",
"                                                    </div>",
"                                                    {note.imageUrl && (",
"                                                        <img",
"                                                            src={note.imageUrl}",
"                                                            alt=\"Saved note image\"",
"                                                            className=\"mt-4 w-full rounded-3xl object-cover\"",
"                                                        />",
"                                                    )}",
"                                                    <div className=\"mt-4 flex flex-wrap gap-2\">",
"                                                        <button",
"                                                            type=\"button\"",
"                                                            onClick={() => handleEditNote(note.id)}",
"                                                            className=\"inline-flex items-center justify-center rounded-lg border border-border bg-card px-3 py-2 text-sm text-foreground transition hover:bg-card/80\"",
"                                                        >",
"                                                            Edit",
"                                                        </button>",
"                                                        <button",
"                                                            type=\"button\"",
"                                                            onClick={() => handleDeleteNote(note.id)}",
"                                                            className=\"inline-flex items-center justify-center rounded-lg border border-border bg-card px-3 py-2 text-sm text-foreground transition hover:bg-red-50 hover:text-red-600\"",
"                                                        >",
"                                                            Delete",
"                                                        </button>",
"                                                    </div>",
"                                                </div>",
"                                            ))}",
"                                        </div>",
"                                    )}",
"                                </div>",
"                            </div>",
"                        )}" ]
if len(lines) < end:
    raise SystemExit(f'File too short: {len(lines)} lines')
lines = lines[:start] + new_block + lines[end:]
path.write_text('\n'.join(lines) + '\n')
print('Replacement complete')
